#!/usr/bin/env bash
set -eu

if [ ! -f .env ]; then
    export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
    vault login -method=github
    GS2YT_SHEET_ID=$(vault read -field=id /secret/hint/gs2yt/googlesheet)
    GS2YT_YT_TOKEN=$(vault read -field=token /secret/hint/gs2yt/youtrack)

    cat <<EOF > .env
GS2YT_SHEET_ID=${GS2YT_SHEET_ID}
GS2YT_YT_TOKEN=${GS2YT_YT_TOKEN}
EOF
fi

IMAGE=reside/gs2yt:mrc-1130
docker pull $IMAGE

mkdir -p data
docker run --rm -d \
       --name=gs2yt \
       --env-file=.env \
       --user="$(id -u):$(id -g)" \
       -v ${PWD}/data:/gs2yt/data \
       $IMAGE
