#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common
docker push $TAG_SHA
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
   docker tag $TAG_BRANCH $TAG_LATEST
   docker push $TAG_LATEST
fi
